# Site settings
title: Back to the Room
title_long: Back to the Room - Blog de passionnés d'escape games
# email: moilotou@backtotheroom.com
description: Aventures d'un couple passionné d'escape games
baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://backtotheroom.com' # the base hostname & protocol for your site
# twitter_username: aspirethemes
# github_username: aspirethemes
facebook_page: backtotheroom

# Build settings
markdown: kramdown
permalink: /:title/
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
gems:
  - jekyll-paginate
  - jekyll/tagging

# Pagination
paginate: 12

# Tags
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

authors:
  antoine:
    name: Moilotou
    display_name: Moilotou
    bio: Moilotou, passionné d'escape games, à votre service.
    gravatar: /images/moilotou.jpg
    # email: moilotou@backtotheroom.com
    web: http://backtotheroom.com
    # github: aspirethemes
